// src/routes/discover/+page.svelte
<h1 class="text-4xl font-black">Discover</h1>

<ul class="mt-5 space-y-2 text-lg">
	<li class="flex items-center justify-between">
		<a href="#" class="underline">2024 wrapped</a>
		<p>31/12/2024</p>
	</li>
	<li class="flex items-center justify-between">
		<a href="#" class="underline">My obsession with the artic monkeys</a>
		<p>10/02/2024</p>
	</li>
</ul>

// src/pages/Discover.jsx
import React from "react";
import Sidebar from "../components/Sidebar";
import Post from "../components/Post";

function Discover() {
  return (
    <>
      <Sidebar />
      <div className="h-full flex justify-center">
        <div className="p-10 w-1/3">
          <h1 className="text-4xl font-black">Discover</h1>
          <div className="mt-10 space-y-5">
            <Post
              title="A personal website"
              date="02, Oct, 2024"
              author="Bashbunni"
            />
          </div>
        </div>
      </div>
    </>
  );
}

export default Discover;
