// src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { ActionData } from './$types';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';

	let { form }: { form: ActionData } = $props();
</script>

<div class="flex items-center justify-center">
	<Card.Root class="w-full max-w-sm">
		<Card.Header>
			<Card.Title class="text-2xl">Login</Card.Title>
		</Card.Header>
		<Card.Content>
			<form action="?/login" method="POST" class="grid gap-4" use:enhance>
				<div class="grid gap-2">
					<Label for="username">Username</Label>
					<Input id="username" name="username" type="text" placeholder="johndoe120" required />
				</div>
				<div class="grid gap-2">
					<Label for="password">Password</Label>
					<Input id="password" name="password" type="password" required />
				</div>
				<Button class="w-full" type="submit">Login</Button>
				{#if form?.message}
					<p class="text-red-500">{form?.message}</p>
				{/if}
			</form>
		</Card.Content>
		<Card.Footer>
			<p class="w-full text-center text-sm">
				Don't have an account? <a href="/signup" class="underline">Sign up</a>
			</p>
		</Card.Footer>
	</Card.Root>
</div>

// src/pages/Login.jsx
import React from "react";
import Navbar from "../components/Navbar";
import { Link } from "react-router";

function Login() {
  function handleSubmit(e) {
    e.preventDefault();
  }

  return (
    <>
      <Navbar />
      <div className="h-full flex justify-center">
        <div className="p-4 md:p-10 w-full max-w-xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-black">Login</h1>
          <form className="space-y-3 my-6" onSubmit={handleSubmit}>
            <input
              placeholder="Email"
              type="email"
              className="p-3 w-full bg-transparent border-gruvbox-bg2 border rounded-xl outline-none"
            />
            <input
              placeholder="Username"
              type="text"
              className="p-3 w-full bg-transparent border-gruvbox-bg2 border rounded-xl outline-none"
            />
            <input
              placeholder="Password"
              type="password"
              className="p-3 w-full bg-transparent border-gruvbox-bg2 border rounded-xl outline-none"
            />
            <button className="bg-gruvbox-fg text-gruvbox-bg w-full p-3 rounded-xl font-bold transition-all hover:opacity-85 active:opacity-70">
              Login
            </button>
          </form>
          <Link to="/signup" className="underline">
            Don't have an account?
          </Link>
        </div>
      </div>
    </>
  );
}

export default Login;
