// src/routes/signup/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { ActionData } from '../signup/$types';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';

	let { form }: { form: ActionData } = $props();
</script>

<Card.Root class="w-full max-w-sm">
	<Card.Header>
		<Card.Title class="text-2xl">Signup</Card.Title>
	</Card.Header>
	<Card.Content>
		<form action="?/register" method="POST" class="grid gap-4" use:enhance>
			<div class="grid gap-2">
				<Label for="username">Username</Label>
				<Input id="username" name="username" type="text" placeholder="johndoe120" required />
			</div>
			<div class="grid gap-2">
				<Label for="password">Password</Label>
				<Input id="password" name="password" type="password" required />
			</div>
			<Button class="w-full" type="submit">Signup</Button>
			{#if form?.message}
				<p class="text-red-500">{form?.message}</p>
			{/if}
		</form>
	</Card.Content>
	<Card.Footer>
		<p class="w-full text-center text-sm">
			Already have an account? <a href="/login" class="underline">Login</a>
		</p>
	</Card.Footer>
</Card.Root>

// app/routes/signup.tsx
import type { MetaFunction } from "@remix-run/node";
import { Form, Link } from "@remix-run/react";

export const meta: MetaFunction = () => {
  return [
    { title: "Elm" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

function signup() {
  return (
    <>
      <h1 className="text-3xl md:text-4xl font-black text-gruvbox-contrast">
        Signup
      </h1>
      <Form className="mt-8 space-y-4">
        <div>
          <label>Name</label>
          <input
            type="text"
            className="input border-1 border-base-200 w-full max-w-xs"
            placeholder="Enter your name"
            required
          />
        </div>
        <div>
          <label>Username</label>
          <input
            type="text"
            className="input border-1 border-base-200 w-full max-w-xs"
            placeholder="Enter your username"
            required
          />
        </div>
        <div>
          <label>Password</label>
          <input
            type="password"
            className="input border-1 border-base-200 w-full max-w-xs"
            placeholder="Enter your password"
            required
          />
        </div>
        <button className="btn w-full text-lg">Signup</button>
        <Link className="text-gruvbox-muted" to="/login">
          Already have an account?
        </Link>
      </Form>
    </>
  );
}

export default signup;
