// app/routes/login.tsx
import type { MetaFunction } from "@remix-run/node";
import { Form, Link } from "@remix-run/react";

export const meta: MetaFunction = () => {
  return [
    { title: "Elm" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

function login() {
  return (
    <>
      <h1 className="text-3xl md:text-4xl font-black text-gruvbox-contrast">
        Login
      </h1>
      <Form className="mt-8 space-y-4">
        <div>
          <label>Username</label>
          <input
            type="text"
            className="input border-1 border-base-200 w-full max-w-xs"
            placeholder="Enter your username"
            required
          />
        </div>
        <div>
          <label>Password</label>
          <input
            type="password"
            className="input border-1 border-base-200 w-full max-w-xs"
            placeholder="Enter your password"
            required
          />
        </div>
        <button className="btn w-full text-lg">Login</button>
        <Link className="text-gruvbox-muted" to="/signup">
          Don't have an account?
        </Link>
      </Form>
    </>
  );
}

export default login;

// src/routes/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { ActionData } from './$types';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';

	let { form }: { form: ActionData } = $props();
</script>

<Card.Root class="w-full max-w-sm">
	<Card.Header>
		<Card.Title class="text-2xl">Login</Card.Title>
	</Card.Header>
	<Card.Content>
		<form action="?/login" method="POST" class="grid gap-4" use:enhance>
			<div class="grid gap-2">
				<Label for="username">Username</Label>
				<Input id="username" name="username" type="text" placeholder="johndoe120" required />
			</div>
			<div class="grid gap-2">
				<Label for="password">Password</Label>
				<Input id="password" name="password" type="password" required />
			</div>
			<Button class="w-full" type="submit">Login</Button>
			{#if form?.message}
				<p class="text-red-500">{form?.message}</p>
			{/if}
		</form>
	</Card.Content>
	<Card.Footer>
		<p class="w-full text-center text-sm">
			Don't have an account? <a href="/signup" class="underline">Sign up</a>
		</p>
	</Card.Footer>
</Card.Root>
